<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOGIN Panel_txtUsername</name>
   <tag></tag>
   <elementGuidId>3214046f-feeb-436c-ab98-78fc7d309d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUsername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af4d7d61-edb6-4cfc-8932-79059371c416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUsername</value>
      <webElementGuid>6a162236-6d04-4282-ae6b-f5f5455f94eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUsername</value>
      <webElementGuid>1240cca6-fb66-4fd1-b814-c774a4956557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb697da9-2c03-4a6b-a074-8e60bf08cd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUsername&quot;)</value>
      <webElementGuid>c01bfb85-ee56-44e5-bf83-b7fc5d2ea707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUsername']</value>
      <webElementGuid>77e8dc78-5f70-4b22-98a8-efcd7e04a426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divUsername']/input</value>
      <webElementGuid>e6c026ea-078f-407b-9f21-0a7ca0c88b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0e25609b-4cfb-4d7b-8e16-af6889e51c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtUsername' and @id = 'txtUsername' and @type = 'text']</value>
      <webElementGuid>57ad351c-5998-479b-9e30-7bc528b6900d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
